# Site settings
baseurl = "http://nii236.github.io/technical-blog/"
languageCode = "en-us"
title = "A Blog"
theme = "hugo-theme-blueberry-detox"

[params]
	name = "John Nguyen"
	description = "Explorations in tech"
	bio = "Engineer - Developer - Traveller"
	# Enter optionally your twitter account
	twitter = "nii236"
	# Disable comments by leaving disqusShortname empty
	disqusShortname = "nii236"
	# Enter your tracking code to enable Google Analytics
	googleAnalytics = "UA-67751474-2"
	enableRSS = true

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = "About"
	subscribe = "RSS"
	# Pagination links
	olderPosts = "Back in time..."
	newerPosts = "Forward in time..."
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I am an aspiring developer"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""
